kind: pipeline
type: docker
name: build
steps:
  - name: build
    image: golang:1.16-alpine
    pull: if-not-exists # always never
    environment:
      KEY: VALUE
    commands:
      - echo $KEY
      - pwd
      - ls
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
      - ./app

trigger:
  branch:
    - master