kind: pipeline
type: docker
name: build
steps:
  - name: build
    image: golang:1.16-alpine
    pull: if-not-exists # always never
    environment:
      KEY: VALUE
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://goproxy.cn
    commands:
      - echo $KEY
      - pwd
      - ls
#      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

  - name: publish
    image: plugins/docker
    repo: dierbei/drone-demo
    dockerfile: ./Dockerfile
    tags: latest
    secrets: [ docker_username, docker_password ]

trigger:
  branch:
    - master